language: java
 
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
  
./gradlew assemble
./gradlew build


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1f1954c1e3206d02f88e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
#Your unique webhook url for this service:

#https://webhooks.gitter.im/e/1f1954c1e3206d02f88e
